# Create a GitHub Actions workflow YAML file that runs a Python script to regenerate images.json
# whenever new images are pushed to the 'images/' folder.

name: Update images

on:
  push:
    paths:
      - 'images/**'
      - 'gen_images_json.py'

jobs:
  generate-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run image list generator
        run: python gen_images_json.py

      - name: Commit updated images.json
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add images.json
          git commit -m "Auto-update images.json via GitHub Actions" || echo "No changes to commit"
          git push